disabled_rules:
    - line_length
    - trailing_whitespace
    - identifier_name
opt_in_rules:
    - empty_count
    - unused_optional_binding
excluded:
    - Carthage
    - Pods
type_body_length:
  warning: 500
  error: 500
file_lenght:
  warning: 550
  error: 600

